#!/bin/sh

pushd ~/scratch/prodlogs
rm catalina_*

for i in 1 2
do
    sftp tomcat@uapp$i.prod.fs.local <<EOF
get /opt/tomcat/logs/catalina.out ./catalina_app$i.log
get /opt/tomcat_ws/logs/catalina.out ./catalina_ws$i.log

EOF
done

for i in 1 2
do
    sftp tomcat@urep$i.prod.fs.local <<EOF
get /opt/tomcat_ws/logs/catalina.out ./catalina_rep$i.log

EOF
done

for i in catalina_*.log
do
    sed -i.org -f sed.commands $i
done

popd
